language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - mysql -e 'create database buchhaltung_test;'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # wait for xvfb
  - "wget http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar"
  - "java -jar selenium-server-standalone-2.46.0.jar > /dev/null 2>/dev/null &"
  - sleep 10 # wait for selenium

matrix:
  allow_failures:
    - php: 5.5
    - php: 5.6

install:
   - composer install

script: phpunit
