language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - mysql -e 'create database buchhaltung_test;'

matrix:
  allow_failures:
    - php: 5.5
    - php: 5.6

install:
   - composer install

script: phpunit
